-- Octo.nvim - GitHub pull request and issue management in Neovim

return {
  {
    "pwntester/octo.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim",
      "nvim-tree/nvim-web-devicons",
    },
    cmd = "Octo",
    config = function()
      require("octo").setup({
        use_local_fs = false,
        enable_builtin = true,
        default_remote = { "upstream", "origin" },
        default_merge_method = "commit",
        ssh_aliases = {},
        picker = "telescope",
        picker_config = {
          use_emojis = true,
        },
        comment_icon = "▎",
        outdated_icon = "󰅒 ",
        resolved_icon = " ",
        reaction_viewer_hint_icon = " ",
        user_icon = " ",
        timeline_marker = " ",
        timeline_indent = "2",
        right_bubble_delimiter = "",
        left_bubble_delimiter = "",
        github_hostname = "",
        snippet_context_lines = 4,
        gh_cmd = "gh",
        gh_env = {},
        timeout = 5000,
        ui = {
          use_signcolumn = true,
        },
        issues = {
          order_by = {
            field = "CREATED_AT",
            direction = "DESC",
          },
        },
        pull_requests = {
          order_by = {
            field = "CREATED_AT",
            direction = "DESC",
          },
          always_select_remote_on_create = false,
        },
        file_panel = {
          size = 10,
          use_icons = true,
        },
        mappings = {
          pull_request = {
            checkout_pr = { lhs = "<space>po", desc = "checkout PR" },
            list_commits = { lhs = "<space>pc", desc = "list PR commits" },
            list_changed_files = { lhs = "<space>pf", desc = "list PR changed files" },
            show_pr_diff = { lhs = "<space>pd", desc = "show PR diff" },
            reload = { lhs = "<C-r>", desc = "reload PR" },
            open_in_browser = { lhs = "<C-b>", desc = "open PR in browser" },
            copy_url = { lhs = "<C-y>", desc = "copy url to system clipboard" },
            goto_file = { lhs = "gf", desc = "go to file" },
            add_assignee = { lhs = "<space>aa", desc = "add assignee" },
            remove_assignee = { lhs = "<space>ad", desc = "remove assignee" },
            add_comment = { lhs = "<space>ca", desc = "add comment" },
            delete_comment = { lhs = "<space>cd", desc = "delete comment" },
            next_comment = { lhs = "]c", desc = "go to next comment" },
            prev_comment = { lhs = "[c", desc = "go to previous comment" },
            react_hooray = { lhs = "<space>rp", desc = "add/remove 🎉 reaction" },
            react_heart = { lhs = "<space>rh", desc = "add/remove ❤️ reaction" },
            react_eyes = { lhs = "<space>re", desc = "add/remove 👀 reaction" },
            react_thumbs_up = { lhs = "<space>r+", desc = "add/remove 👍 reaction" },
            react_thumbs_down = { lhs = "<space>r-", desc = "add/remove 👎 reaction" },
            react_rocket = { lhs = "<space>rr", desc = "add/remove 🚀 reaction" },
            react_laugh = { lhs = "<space>rl", desc = "add/remove 😄 reaction" },
            react_confused = { lhs = "<space>rc", desc = "add/remove 😕 reaction" },
          },
          review_thread = {
            add_comment = { lhs = "<space>ca", desc = "add comment" },
            add_suggestion = { lhs = "<space>sa", desc = "add suggestion" },
            delete_comment = { lhs = "<space>cd", desc = "delete comment" },
            next_comment = { lhs = "]c", desc = "go to next comment" },
            prev_comment = { lhs = "[c", desc = "go to previous comment" },
            select_next_entry = { lhs = "]q", desc = "move to previous changed file" },
            select_prev_entry = { lhs = "[q", desc = "move to next changed file" },
            select_first_entry = { lhs = "[Q", desc = "move to first changed file" },
            select_last_entry = { lhs = "]Q", desc = "move to last changed file" },
            close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
            react_hooray = { lhs = "<space>rp", desc = "add/remove 🎉 reaction" },
            react_heart = { lhs = "<space>rh", desc = "add/remove ❤️ reaction" },
            react_eyes = { lhs = "<space>re", desc = "add/remove 👀 reaction" },
            react_thumbs_up = { lhs = "<space>r+", desc = "add/remove 👍 reaction" },
            react_thumbs_down = { lhs = "<space>r-", desc = "add/remove 👎 reaction" },
            react_rocket = { lhs = "<space>rr", desc = "add/remove 🚀 reaction" },
            react_laugh = { lhs = "<space>rl", desc = "add/remove 😄 reaction" },
            react_confused = { lhs = "<space>rc", desc = "add/remove 😕 reaction" },
          },
          submit_win = {
            approve_review = { lhs = "<C-a>", desc = "approve review" },
            comment_review = { lhs = "<C-m>", desc = "comment review" },
            request_changes = { lhs = "<C-r>", desc = "request changes review" },
            close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
          },
          review_diff = {
            submit_review = { lhs = "<leader>vs", desc = "submit review" },
            discard_review = { lhs = "<leader>vd", desc = "discard review" },
            add_review_comment = { lhs = "<space>ca", desc = "add a new review comment" },
            add_review_suggestion = { lhs = "<space>sa", desc = "add a new review suggestion" },
            focus_files = { lhs = "<leader>e", desc = "move focus to changed file panel" },
            toggle_files = { lhs = "<leader>b", desc = "hide/show changed files panel" },
            next_thread = { lhs = "]t", desc = "move to next thread" },
            prev_thread = { lhs = "[t", desc = "move to previous thread" },
            select_next_entry = { lhs = "]q", desc = "move to previous changed file" },
            select_prev_entry = { lhs = "[q", desc = "move to next changed file" },
            select_first_entry = { lhs = "[Q", desc = "move to first changed file" },
            select_last_entry = { lhs = "]Q", desc = "move to last changed file" },
            close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
            toggle_viewed = { lhs = "<leader><space>", desc = "toggle viewer viewed state" },
            goto_file = { lhs = "gf", desc = "go to file" },
          },
          file_panel = {
            submit_review = { lhs = "<leader>vs", desc = "submit review" },
            discard_review = { lhs = "<leader>vd", desc = "discard review" },
            next_entry = { lhs = "j", desc = "move to next changed file" },
            prev_entry = { lhs = "k", desc = "move to previous changed file" },
            select_entry = { lhs = "<cr>", desc = "show selected changed file diffs" },
            refresh_files = { lhs = "R", desc = "refresh changed files panel" },
            focus_files = { lhs = "<leader>e", desc = "move focus to changed file panel" },
            toggle_files = { lhs = "<leader>b", desc = "hide/show changed files panel" },
            select_next_entry = { lhs = "]q", desc = "move to previous changed file" },
            select_prev_entry = { lhs = "[q", desc = "move to next changed file" },
            select_first_entry = { lhs = "[Q", desc = "move to first changed file" },
            select_last_entry = { lhs = "]Q", desc = "move to last changed file" },
            close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
            toggle_viewed = { lhs = "<leader><space>", desc = "toggle viewer viewed state" },
          },
        },
      })
    end,
    keys = {
      -- Pull Request commands
      { "<leader>pr", "<noop>", desc = "+pull request" },
      { "<leader>prl", "<cmd>Octo pr list<cr>", desc = "List PRs" },
      { "<leader>prs", "<cmd>Octo pr search<cr>", desc = "Search PRs" },
      { "<leader>pro", "<cmd>Octo pr checkout<cr>", desc = "Checkout PR" },
      { "<leader>prr", "<cmd>Octo review start<cr>", desc = "Start Review" },
      { "<leader>prR", "<cmd>Octo review resume<cr>", desc = "Resume Review" },
      { "<leader>prb", "<cmd>Octo pr browser<cr>", desc = "Open PR in Browser" },
      { "<leader>prf", "<cmd>Octo pr changes<cr>", desc = "List Changed Files" },
      { "<leader>prd", "<cmd>Octo pr diff<cr>", desc = "Show PR Diff" },
      
      -- Comments (available in PR/Issue buffers)
      { "<leader>prc", "<noop>", desc = "+comments", ft = "octo" },
      { "<leader>prca", "<cmd>Octo comment add<cr>", desc = "Add Comment", ft = "octo" },
      { "<leader>prcd", "<cmd>Octo comment delete<cr>", desc = "Delete Comment", ft = "octo" },
      
      -- Reactions (available in PR/Issue buffers)
      { "<leader>prx", "<noop>", desc = "+reactions", ft = "octo" },
      { "<leader>prx+", "<cmd>Octo reaction thumbs_up<cr>", desc = "👍", ft = "octo" },
      { "<leader>prx-", "<cmd>Octo reaction thumbs_down<cr>", desc = "👎", ft = "octo" },
      { "<leader>prxh", "<cmd>Octo reaction heart<cr>", desc = "❤️", ft = "octo" },
      { "<leader>prxe", "<cmd>Octo reaction eyes<cr>", desc = "👀", ft = "octo" },
      { "<leader>prxr", "<cmd>Octo reaction rocket<cr>", desc = "🚀", ft = "octo" },
      { "<leader>prxl", "<cmd>Octo reaction laugh<cr>", desc = "😄", ft = "octo" },
      { "<leader>prxp", "<cmd>Octo reaction hooray<cr>", desc = "🎉", ft = "octo" },
      { "<leader>prxc", "<cmd>Octo reaction confused<cr>", desc = "😕", ft = "octo" },
      
      -- Review commands
      { "<leader>prv", "<noop>", desc = "+review", ft = "octo" },
      { "<leader>prvs", "<cmd>Octo review submit<cr>", desc = "Submit Review", ft = "octo" },
      { "<leader>prvd", "<cmd>Octo review discard<cr>", desc = "Discard Review", ft = "octo" },
      { "<leader>prvc", "<cmd>Octo review comments<cr>", desc = "Review Comments", ft = "octo" },
      { "<leader>prvr", "<cmd>Octo review resume<cr>", desc = "Resume Review", ft = "octo" },
    },
  },
}
